### PR TITLE
Girder side broker config

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by zachmullen** [comment]
I can rebase this once #40 and #41 go in, as it depends on both.

**Comment by jeffbaumes** [comment]
Yes please rebase then I can take a better look.

**Comment by zachmullen** [comment]
Rebased

**Comment by jeffbaumes** [comment]
Was able to coordinate changes by changing broker setting on Romanesco worker and Girder plugin. Worked without needing to restart Girder - nice! LGTM

**Pull request merged**
