### PR TITLE
[Preview] Travis container support

### PR DESCRIPTION
**Pull request by jbeezley**
This currently depends on #77.  (I did that to avoid the need to fix the gaia tests that exist on master, but will soon go away.)  I will rebase this on master once that goes in.  I just wanted to show of the working container support.  The run time is down to 2.5 minutes. :joy_cat:

### CODE REVIEW

**Comment by zachmullen** [comment]
You rock!

**Comment by jbeezley** [comment]
This is ready to go when the tests are done.

**Comment by jeffbaumes** [comment]
2m 33s Travis run. LGTM!

**Comment by jeffbaumes** [comment]
Here comes :racehorse: :runner: :athletic_shoe: !

**Pull request merged**
