### PR TITLE
Scope the entire script so it executes in one step

### PR DESCRIPTION
**Pull request by jeffbaumes**
Use brackets to ensure this. Also ensure the script does not require a trailing newline.

### CODE REVIEW

**Comment by zachmullen** [comment]
@jeffbaumes could you duplicate this PR [here](https://github.com/girder/girder_worker/pulls)?

**Comment by jeffbaumes** [comment]
Sure, but I need push access to girder_worker.

**Comment by zachmullen** [comment]
Whoops, you should now have access.

**Comment by jeffbaumes** [comment]
Done https://github.com/girder/girder_worker/pull/2

**Pull request closed without merging**
