### PR TITLE
Cache large downloads on travis

### PR DESCRIPTION
**Pull request by jbeezley**
The Spark download was terribly slow (~100 KB/s) and occasionally failed, so I set up caching for some of the larger tarballs.  This should speed up the testing a fair amount.

### CODE REVIEW

**Comment by danlamanna** [comment]
LGTM.

**Comment by zachmullen** [comment]
Can I merge this PR?

**Comment by jbeezley** [comment]
Yes, I completely forgot about this.

**Comment by jbeezley** [comment]
Oh fun, the SSL cert on our spark mirror is broken.  I'll put in a new PR.

**Pull request merged**
