### PR TITLE
Encapsulate tests for plugins

### PR DESCRIPTION
**Pull request by danlamanna**
Re #110

### CODE REVIEW

**Comment by zachmullen** [comment]
Thanks, I didn't get around to supporting this in my initial branch :+1:

**Comment by danlamanna** [comment]
@zachmullen If you like how 93d260b implements it, then I'll go ahead and port the rest of the plugin-specific tests over.

I want to make sure that's done right, specifically in regards to coverage, and if we're ok with
```add_python_test(graph PLUGIN vtk PLUGINS_ENABLED vtk)``` as opposed to having CMake pick up on what directory/plugin it is and the user leaving ```PLUGIN vtk``` out.

**Comment by zachmullen** [comment]
:+1:

**Comment by danlamanna** [comment]
5eed106 highlights an inconvenience with having to rename tests because they may exist in a plugin as well as core.

Additionally, I left the table/tree plugin tests in core because some of them use converters from the ```vtk``` plugin *and* the ```r``` plugin, so they are codependent but it doesn't make sense to group them together.

**Comment by danlamanna** [comment]
Ready for review.

**Comment by zachmullen** [comment]
This LGTM

**Pull request merged**
