### PR TITLE
Fixes #114. Update core types/formats docs

### LINKED ISSUE #114: Update type and formats documentation

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by jbeezley** [comment]
This may be a separate issue, but the plugin documentation doesn't really discuss the data types beyond a list of converters and validators.  Can the items you removed here be moved to the plugin documentation or has that changed?

**Comment by zachmullen** [comment]
Good idea, I will do that.

**Comment by aashish24** [comment]
Yay!.. I will have a look it later but will be okay if someone else approves it as well

**Comment by zachmullen** [comment]
@jbeezley I moved the old info over

**Comment by jbeezley** [comment]
LGTM modulo #122.

**Comment by aashish24** [comment]
:+1:

**Pull request merged**
