### PR TITLE
Girder io plugin

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by aashish24** [comment]
:clap: @kotfic are you going to review this branch?

**Comment by aashish24** [comment]
I guess @mgrauer  as well

**Comment by mgrauer** [comment]
I'm definitely not the right person to review this, as I'm not a Romanesco developer and have no context for this PR.

:rabbit:

**Comment by zachmullen** [comment]
Context, for anyone who is interested: simple HTTP IO works well enough for fetching data from girder, but for actually pushing data, it's not sufficient since Girder requires a more complicated upload process than just a single request. So, we created a plugin that leverages the awesome power of `girder_client` to make this possible. This also makes downloading directories from girder more straightforward, as they won't need to be archived by the server and un-archived in the task.

**Comment by mgrauer** [comment]
Sounds like a great idea.

**Comment by kotfic** [comment]
LGTM,  thanks!

**Pull request merged**
