### PR TITLE
Pythonic interface to workflows

### PR DESCRIPTION
**Pull request by kotfic**
This PR implements a pythonic interface to romanesco workflows:

Given the following ```workflow```:

```python
workflow = {
    'mode': 'workflow',
    'inputs': [{
        'default': {
            'data': 10,
            'format': 'number'
        },
        'format': 'number',
        'name': 'a3.a',
        'type': 'number'
    }, {
        'format': 'number',
        'name': 'a2.a',
        'type': 'number'
    }],
    'outputs': [{
        'format': 'number',
        'name': 'out',
        'type': 'number'
    }],
    'steps': [{
        'name': 'a3',
        'task': {
            'inputs': [{
                'format': 'number',
                'name': 'a',
                'type': 'number'
            }],
            'mode': 'python',
            'outputs': [{
                'format': 'number',
                'name': 'b',
                'type': 'number'
            }],
            'script': 'b = a + 3'
        }
    }, {
        'name': 'a2',
        'task': {
            'inputs': [{
                'format': 'number',
                'name': 'a',
                'type': 'number'
            }],
            'mode': 'python',
            'outputs': [{
                'format': 'number',
                'name': 'b',
                'type': 'number'
            }],
            'script': 'b = a + 2'
        }
    }, {
        'name': 'm',
        'task': {
            'inputs': [{
                'format': 'number',
                'name': 'in1',
                'type': 'number'
            }, {
                'format': 'number',
                'name': 'in2',
                'type': 'number'
            }],
            'mode': 'python',
            'outputs': [{
                'format': 'number',
                'name': 'out',
                'type': 'number'
            }],
            'script': 'out = in1 * in2'
        }
    }],
   'connections': [{
        'input': 'a',
        'input_step': 'a3',
        'name': 'a3.a'
    }, {
        'input': 'a',
        'input_step': 'a2',
        'name': 'a2.a'
    }, {
        'input': 'in1',
        'input_step': 'm',
        'output': 'b',
        'output_step': 'a3'
    }, {
        'input': 'in2',
        'input_step': 'm',
        'output': 'b',
        'output_step': 'a2'
    }, {
        'name': 'out',
        'output': 'out',
        'output_step': 'm'
    }],
}

```

This may now be written with the following syntax:

```python

wf = specs.Workflow()

add_two = {
    "inputs": [{"name": "a", "type": "number", "format": "number"}],
    "outputs": [{"name": "b", "type": "number", "format": "number"}],
    "mode": "python",
    "script": "b = a + 2"}

add_three = {
    "inputs": [{"name": "a", "type": "number", "format": "number"}],
    "outputs": [{"name": "b", "type": "number", "format": "number"}],
    "mode": "python",
    "script": "b = a + 3"}

multiply = {
    "inputs": [{"name": "in1", "type": "number", "format": "number"},
               {"name": "in2", "type": "number", "format": "number"}],
    "outputs": [{"name": "out", "type": "number", "format": "number"}],
    "mode": "python",
            "script": "out = in1 * in2"}

wf.add_task(add_two, "a2")
wf.add_task(add_three, "a3")
wf.add_task(multiply, "m")

wf.connect_tasks("a3", "m", {"b": "in1"})
wf.connect_tasks("a2", "m", {"b": "in2"})

# Add default as defined in self.workflow
wf.set_default("a3.a", {"format": "number", "data": 10})
```

If the ```add_two```, ```add_three```, and ```multiply``` spec definitions are in files one may use ```spec_class_generator``` to load these as generic,  dynamic classes inheriting from specs.Task

```python
with open("/path/to/add_two.json", "r") as fh:
    AddTwo = spec_class_generator("AddTwo", fh.read())

with open("/path/to/add_three.json", "r") as fh:
    AddThree = spec_class_generator("AddThree", fh.read())

with open("/path/to/add_three.json", "r") as fh:
    Multiply = spec_class_generator("Multiply", fh.read())

wf = specs.Workflow()

wf.add_task(AddTwo(), "a2")
wf.add_task(AddThree(), "a3")
wf.add_task(Multiply(), "m")

wf.connect_tasks("a3", "m", {"b": "in1"})
wf.connect_tasks("a2", "m", {"b": "in2"})

# Add default as defined in self.workflow
wf.set_default("a3.a", {"format": "number", "data": 10})

```

These classes may also be defined statically as follows:

```python
class AddTwo(specs.Task):
    __inputs__ = specs.PortList([
        {"name": "a", "type": "number", "format": "number"}
    ])
    __outputs__ = specs.PortList([
        {"name": "b", "type": "number", "format": "number"}
    ])
    
    def __init__(self, spec=None, **kw):
        super(AddTwo, self).__init__(spec, **kw)
        self.mode = "python"
        self.script = "b = a + 2"
        
class AddThree(specs.Task):
    __inputs__ = specs.PortList([
        {"name": "a", "type": "number", "format": "number"}
    ])
    __outputs__ = specs.PortList([
        {"name": "b", "type": "number", "format": "number"}
    ])
    
    def __init__(self, spec=None, **kw):
        super(AddThree, self).__init__(spec, **kw)
        self.mode = "python"
        self.script = "b = a + 3"
        
class Multiply(specs.Task):
    __inputs__ = specs.PortList([
        {"name": "in1", "type": "number", "format": "number"},
        {"name": "in2", "type": "number", "format": "number"}
    ])
    __outputs__ = specs.PortList([
        {"name": "out", "type": "number", "format": "number"}
    ])
    
    def __init__(self, spec=None, **kw):
        super(Multiply, self).__init__(spec, **kw)
        self.mode = "python"
        self.script = "out = in1 * in2"
        
wf = specs.Workflow()

wf.add_task(AddTwo(), "a2")
wf.add_task(AddThree(), "a3")
wf.add_task(Multiply(), "m")

wf.connect_tasks("a3", "m", {"b": "in1"})
wf.connect_tasks("a2", "m", {"b": "in2"})

# Add default as defined in self.workflow
wf.set_default("a3.a", {"format": "number", "data": 10})
```

Finally,  in all three cases the following assertions are True

```python

TestCase.assertEquals(wf, workflow)

inputs = {"a2.a": {"format": "json", "data": "1"},
          "a3.a": {"format": "number", "data": 2}}

ground = romanesco.run(workflow, inputs=inputs)
system = romanesco.run(wf, inputs=inputs)

TestCase.assertEquals(system, ground)
```

### CODE REVIEW

**Comment by curtislisle** [comment]
I like the pythonic API. It will be easier for non-JSON programmers to understand. I like the purity of type assertions and the function generator. Nice.

**Comment by jbeezley** [comment]
Very nice! :+1:

**Comment by jeffbaumes** [comment]
This looks very good, nice! I could see `connect_tasks` doing the "right thing" if the first arg only has one output, the second arg only has one input, and there is no third arg. That is, it will connect the output to the input. I could also see a minor change where there are always two arguments that can either be pairs (to specify the port) or strings (to assume the only - or perhaps first - port):

```
connect_tasks('a3', 'm')
connect_tasks(('a3', 'b'), ('m', 'in2'))
connect_tasks(('a3', 'b'), 'm')
connect_tasks('a3', ('m', 'in2'))
```

They could also be dicts (six or half-dozen compared to pairs):

```
connect_tasks('a3', 'm')
connect_tasks({'a3': 'b'}, {'m': 'in2'})
connect_tasks({'a3': 'b'}, 'm')
connect_tasks('a3', {'m': 'in2'})
```

But I also think your API is fine if you don't think these are better.

**Comment by jeffbaumes** [comment]
That this works in all 3 cases is somewhat mind-blowing:
```
TestCase.assertEquals(wf, workflow)
```
:+1:

**Comment by aashish24** [comment]
Looks Great @kotfic!! :clap: my only wish would be index based option vs named option for the port but that could be done later. SHIP IT!

**Comment by jeffbaumes** [comment]
LGTM too

**Pull request merged**
