### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by ferambot**
Hi, I am Feram,

I'm a bot and I work on behalf of [Adrian][adius].
If my merge request helped to improve this repository,
please consider to [star my repo][repo] to show some love! 😊

If I didn't behave, you can [create an issue][issues]
and my dad will try to fix me.

Love, hugs and kisses,
your [Feram][feram]

[adius]: https://github.com/adius
[feram]: https://github.com/ferambot
[repo]: https://github.com/ferambot/feram
[issues]: https://github.com/ferambot/feram/issues

### CODE REVIEW

**Comment by zachmullen** [comment]
Bots are the only ones still maintaining this repository. Should we go ahead and shut down romanesco?

**Comment by jeffbaumes** [comment]
Yes. I think we should turn it into a stub repo that just has a README that points to Girder Worker. You are welcome to do so.

**Comment by curtislisle** [comment]
thanks for leaving the stub repo.  This repo is still needed for the older Arbor (Flow with romanesco) playbooks to function.  The old playbooks are hard-coded for a previous commit number, so they still function.  Please don’t totally delete the repository until our total girder-based version of Flow is stable.  Thanks. 

Curt

**Comment by jeffbaumes** [comment]
Yes, good point. Will do.

**Pull request closed without merging**
