### PR TITLE
Get not implemented by mutable mapping

### PR DESCRIPTION
**Pull request by kotfic**

### CODE REVIEW

**Comment by jeffbaumes** [comment]
I assume there is a test that can be added here. Is this part of making sure `json.dumps` works?

**Comment by zachmullen** [comment]
From my end, it would be great if such a test could try to write one of these objects into mongodb using pymongo. (We already depend on mongodb in our table_test.)

**Comment by kotfic** [comment]
@jeffbaumes @zachmullen No actually,  there are just several places where get() is used to access items (e.g., https://github.com/Kitware/romanesco/blob/master/romanesco/plugins/spark/__init__.py#L15)  - apparently the MutableMapping doesn't implement this by default.  I haven't started looking at the json.dumps stuff yet

Also is travis not working correctly?

```
$ R --version
/home/travis/build.sh: line 41: R: command not found

The command "R --version" failed and exited with 127 during .
```

**Comment by jeffbaumes** [comment]
Hm yeah I restarted one of the builds but it failed again. Not sure why it's not picking up R. @jbeezley, any ideas?

**Comment by jbeezley** [comment]
This I think:
```
$ eval "$(curl https://data.kitware.com/api/v1/file/55735da88d777f649a9ba181/download | /bin/bash)"

curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

**Comment by danlamanna** [comment]
I wonder if that may have something to do with the somewhat recent changes we had done to data.kitware.com regarding the girder-cli requiring a scheme. @zachmullen

**Comment by jbeezley** [comment]
That command works for me locally.  With @jeffbaumes's issue, I wonder if there is something going on with `data.kitware.com`.  Possibly when accessed outside our network?

**Comment by kotfic** [comment]
@jeffbaumes this passes locally (exception of some swift tests that i assume i don't have dependencies for).  I can keep developing on minerva on this branch but it would be nice to merge this if possible.

**Comment by jbeezley** [comment]
Can anyone else reproduce this?
```
$ wget https://data.kitware.com/api/v1/file/55735da88d777f649a9ba181/download
--2015-09-15 15:12:50--  https://data.kitware.com/api/v1/file/55735da88d777f649a9ba181/download
Resolving data.kitware.com (data.kitware.com)... 192.168.120.113
Connecting to data.kitware.com (data.kitware.com)|192.168.120.113|:443... connected.
ERROR: The certificate of ‘data.kitware.com’ is not trusted.
ERROR: The certificate of ‘data.kitware.com’ hasn't got a known issuer.
```

**Comment by cjh1** [comment]
Works for me

**Comment by cpatrick** [comment]
Works for me, too.

-Patrick

**Comment by jbeezley** [comment]
So this is happening on travis
```
$ curl -v https://data.kitware.com/api/v1/file/55735da88d777f649a9ba181/download
* About to connect() to data.kitware.com port 443 (#0)
*   Trying 50.58.123.189... connected
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS alert, Server hello (2):
* error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
* Closing connection #0
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

**Comment by jeffbaumes** [comment]
Naive google search found this - might be related? https://github.com/travis-ci/travis-ci/issues/4757

**Comment by jbeezley** [comment]
Travis is connecting via `https://50.58.123.189/api/v1/file/55735da88d777f649a9ba181/download` which fails here as well:

```
$ curl -v https://50.58.123.189/api/v1/file/55735da88d777f649a9ba181/download
*   Trying 50.58.123.189...
* Connected to 50.58.123.189 (50.58.123.189) port 443 (#0)
* WARNING: using IP address, SNI is being disabled by the OS.
* SSL: certificate verification failed (result: 5)
* Closing connection 0
curl: (51) SSL: certificate verification failed (result: 5)
```

If you ignore the error, then the file downloads successfully.

**Comment by jbeezley** [comment]
@jeffbaumes Looks like the issue linked is relevant.  `data.kitware.com` only supports TLS 1.2.  I'll try updating some of the installed libraries to see if it helps.

**Comment by kotfic** [comment]
@jeffbaumes @jbeezley  cool... but could someone review the PR? thanks :smile:

**Comment by jbeezley** [comment]
The error should be fixed by #155.  This change LGTM.

**Comment by jeffbaumes** [comment]
I was looking for a test for this change before merge, @kotfic. Sorry if that wasn't clear. Should be easy to do.

**Comment by zachmullen** [comment]
@jbeezley Should we consider exposing earlier TLS versions on data.kitware.com? Which version does travis need?

**Comment by kotfic** [comment]
@jeffbaumes derp,  totally missed that -  adding now

**Comment by jbeezley** [comment]
Probably 1.1 would work.  The issue seems to a buggy openssl.  There were a number of bug fixes/reverts and disabling of different TLS features in openssl that went on since 12.04 was released.  Other TLS 1.2 sites work, there must be some some combination of cipher and handshake protocol triggering the bug.

This is a pretty complete analysis tool for SSL support[1].  In the current setup, older browsers won't be supported.

[1] https://www.ssllabs.com/ssltest/analyze.html?d=data.kitware.com

**Comment by zachmullen** [comment]
Thanks for the explanation and link, I'm going to forward that to data.kitware.com sysadmin so they are aware.

**Comment by jeffbaumes** [comment]
@kotfic I ran tests manually, LGTM. I say we merge and we can continue the discussion here or (better) move the discussion to another issue.

**Pull request merged**
