### PR TITLE
Added new types to support translation from slicer xml

### PR DESCRIPTION
**Pull request by cdeepakroy**
Added new types to support the automatic creation of REST end points from the [xml spec of a slicer execution model CLI](https://www.slicer.org/slicerWiki/index.php/Slicer3:Execution_Model_Documentation#XML_Schema)

### CODE REVIEW

**Comment by cdeepakroy** [comment]
@jeffbaumes @zachmullen can you take a look?

**Comment by zachmullen** [comment]
Can we make this change against github.com/girder/girder_worker?

**Comment by zachmullen** [comment]
Nevermind, looks like you already did. https://github.com/girder/girder_worker/pull/6/files

**Comment by aashish24** [comment]
@zachmullen @jeffbaumes  is there a reason keep this repo alive now?

**Comment by zachmullen** [comment]
I would like to sunset new PRs into this repo ASAP. If there are any outstanding projects that need to be ported over to girder_worker, I am happy to help with that conversion process.

**Comment by jeffbaumes** [comment]
+1. The flow app needs to migrate as one example.

**Pull request closed without merging**
